# Generated by Django 5.2.17 on 2026-09-25 16:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(20, 0), '08:00 PM')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SlotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(20, 0), '08:00 PM')])),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment_date', 'appointment_time'), name='unique_date_time_capacity')],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='sent', max_length=30)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='appointments.appointment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment', 'event_type'), name='unique_appointment_email_event')],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time', 'status'], name='appointment_appoint_4c2c13_idx'),
        ),
    ]
