# Generated by Django 5.2.17 on 2026-09-26 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_scheduledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(20, 0), '08:00 PM')], null=True),
        ),
        migrations.AlterField(
            model_name='slotcapacity',
            name='appointment_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(20, 0), '08:00 PM')], null=True),
        ),
    ]
