# Generated by Django 5.2.17 on 2026-09-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
